baseurl: "FruitCake"
theme: jekyll-theme-slate
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Ingredients.md
  - Recipe.md
